#!/bin/bash



current_dir=$(pwd)

parent_dir=$(dirname "$current_dir")



for file in *.html; do

  if [ -f "$parent_dir/$file" ]; then

    if [ "$file" -nt "$parent_dir/$file" ]; then

      cp "$file" "$parent_dir/$file"

    fi

  else

    cp "$file" "$parent_dir/$file"

  fi

done
